# Site settings
title: Simple thoughts of complex man
email: davor_nedic@hotmail.com
description: "Personal website of Davor Nedic, regarding Java programing, JavaScript, HTML, CSS and mobile app development"
baseurl: ""
url: "http://tnedich.github.io"
twitter_username: tnedich
github_username:  tnedich

# Build settings
markdown: kramdown
permalink: pretty
